INSERT INTO comment (id, user_id, ad_id, text) VALUES (1,3,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (2,7,1,'Lost in the labyrinth of her thoughts, she searched for a way out.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (3,2,2,'The melody danced through the room, carrying the weight of nostalgia.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (4,5,3,'The soft petals of the rose embraced the morning dew, glistening under the sunlight.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (5,4,5,'In the depths of the forest, a hidden treasure awaited its fortunate discoverer.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (6,1,8,'Whispers of the wind carried secrets from distant lands, whispering tales of adventure.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (7,32,11,'The stars adorned the night sky, like diamonds scattered across a dark canvas.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (8,3,13,'The waves crashed against the shore, creating a symphony of nature s power.')
INSERT INTO comment (id, user_id, ad_id, text) VALUES (9,13,15,'With each step, the hiker ventured further into the wilderness, guided by his adventurous spirit.')
