services:

  advertising-service:
    build: ./advertising-service/server
    container_name: advertising-service
    ports:
      - '8081:8081'

  comment-service:
    build: ./comment-service/server
    container_name: comment-service
    ports:
      - '8080:8080'

  cowork-gateway:
    depends_on:
      - user-db
    build: ./cowork-gateway/server
    container_name: cowork-gateway
    env_file:
      - spring.env
      - postgres.env
    ports:
      - '8082:8082'

  user-db:
    image: postgres:16.1-alpine
    container_name: user-db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - "5432:5432"

  frontend:
    build: ./cowork-gateway/web/cowork-web
    container_name: frontend
    ports:
      - '4202:4202'
    volumes:
      - angular:/var/lib/project/.angular
      - npm-modules:/var/lib/project/node_modules

volumes:
  db-data:
  angular:
  npm-modules:
