INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (1, 1, 'test text', 'test@test.com', 1, 'test city', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (2, 1, 'test text2', 'test2@test.com', 2, 'test city2', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (3, 3, 'example text', 'example@example.com', 2, 'example city', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (4, 5, 'Lorem ipsum dolor sit amet', 'lorem@ipsum.com', 3, 'consectetur adipiscing elit', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (5, 7, 'Hello world!', 'hello@world.com', 4, 'Mars', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (6, 9, 'The quick brown fox jumps over the lazy dog', 'quick@brownfox.com', 5, 'New York', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (7, 11, 'To be or not to be, that is the question', 'hamlet@shakespeare.com', 6, 'London', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (8, 13, 'Life is like a box of chocolates, you never know what you are gonna get', 'forrest@gump.com', 7, 'Alabama', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (9, 15, 'I have a dream', 'martin@lutherking.com', 8, 'Washington D.C.', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (10, 17, 'One small step for man, one giant leap for mankind', 'neil@armstrong.com', 9, 'Moon', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (11, 19, 'The only way to do great work is to love what you do', 'steve@jobs.com', 10, 'San Francisco', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (12, 21, 'Education is the most powerful weapon which you can use to change the world', 'nelson@mandela.com', 11, 'Johannesburg', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (13, 23, 'I think, therefore I am', 'rene@descartes.com', 12, 'Paris', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (14, 27, 'Imagination is more important than knowledge', 'albert@einstein.com', 14, 'Princeton', true, false)
INSERT INTO advertising (id, user_id, text, email, priority, address, is_active, is_favorite) VALUES (15, 31, 'The future belongs to those who believe in the beauty of their dreams', 'eleanor@roosevelt.com', 16, 'New York', true, false)

INSERT INTO advertising_category VALUES (1, 'Programmer')
INSERT INTO advertising_category VALUES (1, 'Security')
INSERT INTO advertising_category VALUES (2, 'Video Editor')
INSERT INTO advertising_category VALUES (3, 'Programmer')
INSERT INTO advertising_category VALUES (4, 'Programmer')
INSERT INTO advertising_category VALUES (5, 'Programmer')
INSERT INTO advertising_category VALUES (6, 'Programmer')
INSERT INTO advertising_category VALUES (7, 'Programmer')
INSERT INTO advertising_category VALUES (8, 'Programmer')
INSERT INTO advertising_category VALUES (10, 'Programmer')
INSERT INTO advertising_category VALUES (11, 'Programmer')
INSERT INTO advertising_category VALUES (12, 'Programmer')
INSERT INTO advertising_category VALUES (13, 'Programmer')
INSERT INTO advertising_category VALUES (14, 'Programmer')
INSERT INTO advertising_category VALUES (15, 'Programmer')

INSERT INTO rating (id, user_id, rating_value) VALUES (1, 1, 3)
INSERT INTO rating (id, user_id, rating_value) VALUES (2, 1, 5)
INSERT INTO rating (id, user_id, rating_value) VALUES (3, 2, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (4, 3, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (5, 4, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (6, 5, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (7, 7, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (8, 9, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (9, 11, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (10, 13, 4)
INSERT INTO rating (id, user_id, rating_value) VALUES (11, 15, 4)