server.port: 8082

spring:
  application.name: cowork-gateway
  datasource:
    url: jdbc:postgresql://${HOST_ADDRESS}:5432/${POSTGRES_DB}
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changeLog/db.changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.elasticsearch.client.WIRE: trace

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
