server.port: 8082

spring:
  application.name: cowork-gateway

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.elasticsearch.client.WIRE: trace

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
